In [ ]:
#Q1 - Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

NumPy, short for "Numerical Python," is a powerful library used in scientific computing and data analysis. It extends Python’s capabilities for handling large amounts of numerical data and performing complex mathematical operations efficiently. Here's how NumPy enhances Python and its key advantages:

Purpose of NumPy:
Efficient handling of large datasets: NumPy provides support for multi-dimensional arrays (often referred to as ndarrays) that allow for efficient storage and manipulation of large datasets, which is critical in scientific computing.
Mathematical functions and operations: It includes a large collection of mathematical functions that operate on these arrays, such as linear algebra operations, random number generation, Fourier transforms, and more.
Performance optimization: NumPy is designed to perform operations on large arrays of data much faster than traditional Python lists by using highly optimized C and Fortran code under the hood.
Advantages of NumPy in Scientific Computing and Data Analysis:
Fast and Memory Efficient: NumPy arrays are more efficient than Python lists in terms of both speed and memory usage. They are stored in contiguous memory locations, which allows for rapid computation, while Python lists are more general-purpose but slower due to overhead and flexibility.

Vectorization: NumPy allows vectorized operations, meaning you can apply operations across entire arrays or matrices without writing explicit loops. This enhances performance, simplifies code, and is more in line with mathematical notation.

In [1]:
#example of vectorization
import numpy as np
arr = np.array([1, 2, 3, 4])
result = arr * 2  # Each element is multiplied by 2


Broadcasting: NumPy allows broadcasting, which is the ability to perform arithmetic operations on arrays of different shapes in a memory-efficient way. For example, you can add a scalar to a multi-dimensional array or perform operations between arrays of different sizes without copying data unnecessarily.

In [2]:
#Example of broadcasting:

arr1 = np.array([1, 2, 3])
arr2 = np.array([[1], [2], [3]])
result = arr1 + arr2

How NumPy Enhances Python’s Numerical Capabilities:
Efficiency in Numerical Operations: Python's built-in data structures (e.g., lists) are general-purpose and not optimized for numerical computation. NumPy, however, provides data structures (like ndarrays) that are specialized for numerical operations, offering significant speed improvements (often by several orders of magnitude).

Ease of Use with Complex Operations: Without NumPy, numerical operations, especially with matrices or large datasets, would require custom, slower implementations. With NumPy, operations like matrix multiplications, element-wise arithmetic, or complex transformations are easily executed with simple syntax.

Seamless Parallelism and Caching: NumPy efficiently leverages low-level optimizations, including parallelism and hardware-specific instructions (like SIMD), allowing numerical operations to be highly optimized without the user needing to manage it explicitly.

Overall, NumPy significantly boosts Python's capabilities in scientific computing and data analysis by providing an efficient and user-friendly environment for handling numerical data and performing mathematical operations at scale.

In [ ]:
#Q2 - Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

Both np.mean() and np.average() are functions in NumPy that compute the average of data, but they have distinct differences in terms of behavior, especially regarding weighting. Here’s a detailed comparison and when to use each function:

1. Definition and Basic Use:
np.mean():

Definition: Computes the arithmetic mean (average) of the elements along a specified axis or for the entire array.

Basic Usage: This function gives the simple mean of the data without considering any weights.
arr: Input array.
axis: Axis along which the means are computed. If not specified, the mean of the flattened array is returned.
dtype: Specifies the data type to use during computation (optional)

In [3]:

#example
arr = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(arr)  # Output: 3.0


np.average():

Definition: Computes the weighted average of the elements, where each element can be weighted differently. If no weights are provided, it acts like np.mean().

Basic Usage: This function allows for weighted averages, which means you can specify the weight of each element.
weights: This is the key difference. You can pass an array of the same shape as arr or broadcastable to its shape, where each weight indicates the contribution of the corresponding element to the average.
returned: If True, it returns a tuple where the first element is the weighted average and the second element is the sum of weights.

In [4]:
#Example (without weights):
arr = np.array([1, 2, 3, 4, 5])
avg_value = np.average(arr)  # Output: 3.0 (same as np.mean when weights=None)
#Example (with weights):
arr = np.array([1, 2, 3, 4, 5])
weights = np.array([0.1, 0.2, 0.3, 0.4, 0.5])
weighted_avg = np.average(arr, weights=weights)  # Output: 3.6667

4. Key Difference in Weighted Average:
The major distinction is that np.average() can handle weights, making it more versatile when dealing with real-world data where not all values are equally important, while np.mean() is strictly for computing the arithmetic mean without considering the importance of individual values.

In [ ]:
#Example Highlighting Difference:
arr = np.array([1, 2, 3, 4, 5])

# Mean of the array (equal contribution from all elements)
mean_value = np.mean(arr)  # Output: 3.0

# Weighted average where last element has zero contribution
weights = np.array([1, 1, 1, 1, 0])
weighted_avg = np.average(arr, weights=weights)  # Output: 2.5


Conclusion:
Use np.mean() for simple average calculations when all elements are equally important.
Use np.average() when you need to compute a weighted average, where some elements have more influence than others.

In [ ]:
#Q3 - Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

To reverse a NumPy array along different axes, you can use slicing techniques. Let's explore this for both 1D and 2D arrays:

1D Array
A 1D NumPy array is essentially a simple list of elements. To reverse this array, you can use slicing with the syntax [::-1], which means "slice from start to end with a step of -1."
2D Array
For 2D arrays, you can reverse along different axes using slicing as well. A 2D array can be thought of as a matrix where you can reverse:

Along rows (axis 0)
Along columns (axis 1)

In [6]:
#example 1D
import numpy as np

# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Reverse the 1D array
reversed_1d = arr_1d[::-1]
print(reversed_1d)

#example 2D
# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Reverse the 2D array along rows (axis 0)
reversed_rows = arr_2d[::-1, :]
print("Reversed along rows (axis 0):\n", reversed_rows)

# Reverse the 2D array along columns (axis 1)
reversed_columns = arr_2d[:, ::-1]
print("\nReversed along columns (axis 1):\n", reversed_columns)

# Reverse along both axes
reversed_both_axes = arr_2d[::-1, ::-1]
print("\nReversed along both axes:\n", reversed_both_axes)


[5 4 3 2 1]
Reversed along rows (axis 0):
 [[7 8 9]
 [4 5 6]
 [1 2 3]]

Reversed along columns (axis 1):
 [[3 2 1]
 [6 5 4]
 [9 8 7]]

Reversed along both axes:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


In [ ]:
#Q4 -  How can you determine the data type of elements in a NumPy array? Discuss the importance of data types  in memory management and performance.

To determine the data type of elements in a NumPy array, you can use the dtype attribute.

In [7]:
#Here’s an example:
import numpy as np

arr = np.array([1, 2, 3])
print(arr.dtype)


int64


This will output the data type of the array elements, such as int32, float64, etc.

Importance of Data Types in Memory Management and Performance
Memory Efficiency:

NumPy arrays store data more compactly compared to native Python data structures like lists. The data type defines how much memory each element consumes. For example, an int32 consumes 4 bytes per element, while an int64 consumes 8 bytes. Choosing the appropriate data type ensures efficient memory usage.
If you are working with a large dataset, using a more compact data type can save significant amounts of memory. For example, using uint8 (1 byte) instead of int64 (8 bytes) for values ranging between 0 and 255 drastically reduces memory consumption.
Performance:

NumPy operations are implemented in C and are highly optimized for speed. However, the data type affects performance. Operations on smaller data types (e.g., int16) are typically faster than on larger ones (e.g., int64), since fewer bytes need to be processed.
Vectorized operations in NumPy, such as element-wise addition, take advantage of the fixed-size elements. This uniformity allows the CPU to process data more efficiently compared to Python lists, where elements can have varying types and sizes.
Precision Control:

Data types also allow you to control precision. For example, if you’re working with floating-point numbers, float32 uses less memory than float64 but with reduced precision. This can be important in scenarios like scientific computing, where precision is critical, or image processing, where performance may matter more.
Compatibility:

Specifying the right data type can ensure compatibility when interfacing with external libraries or data formats (e.g., binary files, databases) that expect data in a particular format. This avoids potential errors and reduces the need for conversions.
By carefully selecting the data type, you can balance memory usage, performance, and precision, depending on the needs of your application.

In [ ]:
#Q5 - Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

In NumPy, an ndarray (n-dimensional array) is the core data structure that represents a grid of values, all of the same type, and is indexed by a tuple of non-negative integers. The number of dimensions is defined by the array's shape, a tuple representing the size of the array along each dimension.

Key Features of ndarray:
Homogeneous data types: Every element in an ndarray must have the same data type (e.g., integers, floats, etc.), which is specified at the time of array creation. This leads to efficient memory usage.

Multidimensional: ndarray can have any number of dimensions. The number of dimensions is determined by the array's shape. A 1D array is a vector, a 2D array is a matrix, and higher dimensions are often used in scientific computing.

Fast and efficient operations: NumPy provides optimized implementations of mathematical operations on arrays. These operations are typically performed in C or Fortran under the hood, making them much faster than operations on standard Python lists.

Element-wise operations: Arithmetic operations, like addition, subtraction, and multiplication, are performed element-wise. This allows for vectorized operations that eliminate the need for loops in many cases.

Memory layout and slicing: Arrays are stored in contiguous blocks of memory, making them cache-friendly and enhancing performance. You can slice and access subarrays efficiently without copying data.

Broadcasting: NumPy arrays support broadcasting, which allows operations between arrays of different shapes in a way that aligns smaller arrays to larger ones.

Differences Between ndarray and Python Lists:
Data Type:

In Python lists, elements can have different data types.
In ndarray, all elements must have the same data type, making memory and operations more efficient.
Memory Efficiency:

Python lists store references to the actual data, which leads to greater memory overhead.
ndarray stores elements in a contiguous block of memory, resulting in reduced overhead and faster access times.
Performance:

Lists are slower for mathematical operations because each operation typically involves Python loops.
ndarray is faster because it performs element-wise operations in compiled C code, optimizing performance.
Dimensionality:

Python lists are inherently one-dimensional, but can be nested to represent multi-dimensional structures, though access becomes more cumbersome.
ndarray natively supports n-dimensional arrays, making it straightforward to manipulate and access higher-dimensional data.
Built-in Mathematical Functions:

While Python lists require explicit loops or the use of external libraries for element-wise mathematical operations, NumPy provides many mathematical functions (e.g., sum, mean, dot) that work seamlessly on arrays.

In [13]:
#example
import numpy as np

# Create a 1D array (vector)
arr_1d = np.array([1, 2, 3])

# Create a 2D array (matrix)
arr_2d = np.array([[4, 5, 6], [7, 8, 9]])

# Example of element-wise addition
result_addition = arr_1d + 2  # Adds 2 to each element in arr_1d
print("Element-wise addition result:")
print(result_addition)

# Example of broadcasting
result_broadcasting = arr_2d + arr_1d  # Broadcasting 1D array to match 2D shape
print("\nBroadcasting result:")
print(result_broadcasting)


Element-wise addition result:
[3 4 5]

Broadcasting result:
[[ 5  7  9]
 [ 8 10 12]]


In [12]:
#Q6 - Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations

NumPy arrays offer significant performance benefits over Python lists for large-scale numerical operations due to several key factors:

1. Memory Efficiency
Homogeneous Data Types: NumPy arrays store elements of the same data type, which allows for more efficient memory usage compared to Python lists that can hold elements of different types.
Fixed Size: Unlike Python lists that dynamically resize, NumPy arrays have a fixed size, meaning less memory overhead due to the absence of pointers and dynamic resizing mechanisms. This leads to faster memory allocation.
2. Vectorized Operations
Element-wise Operations: NumPy arrays allow vectorized operations, where operations are performed on entire arrays at once without the need for explicit loops. This takes advantage of low-level optimizations and results in much faster computations than using Python's for-loops on lists.
3. Efficient Broadcasting
Automatic Expansion: NumPy can automatically "broadcast" smaller arrays to match the dimensions of larger arrays when performing operations, avoiding the need to manually replicate data, which is more cumbersome and slower with Python lists.
4. Optimized C and Fortran Libraries
Low-level Implementations: NumPy is implemented in C and Fortran, making it much faster for numerical operations. Python lists rely on high-level Python operations, which are inherently slower than compiled code. NumPy’s optimized backend allows for more efficient execution of mathematical computations.
5. Contiguous Memory Allocation
Better Cache Utilization: NumPy arrays are stored in contiguous blocks of memory, leading to better cache performance. Python lists are arrays of pointers, meaning data can be scattered in memory, reducing cache efficiency.
6. Parallelization
Multi-threading and SIMD: NumPy can take advantage of parallelism (e.g., via multi-threading or SIMD instructions) to speed up operations, especially for large datasets. This is not easily achievable with Python lists.
7. Built-in Mathematical Functions
Highly Optimized Functions: NumPy provides many built-in mathematical functions (e.g., sum, mean, dot, etc.) that are optimized for performance. These functions are faster than using equivalent operations on Python lists.
8. Type-Specific Operations
Avoiding Type Checking Overhead: Since NumPy arrays enforce a single data type, it avoids the overhead of type checking that Python lists incur during runtim


In [14]:
#Performance Comparison Example

import numpy as np
import time

# Large-scale operation with NumPy
size = 10**7
array_np = np.arange(size)

start_time = time.time()
array_np = array_np * 2
print("NumPy operation time:", time.time() - start_time)

# Large-scale operation with Python list
array_py = list(range(size))

start_time = time.time()
array_py = [x * 2 for x in array_py]
print("Python list operation time:", time.time() - start_time)


NumPy operation time: 0.12820196151733398
Python list operation time: 1.3369073867797852


In [15]:
#Q7 - Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and  output


In NumPy, vstack() and hstack() are functions used to stack arrays either vertically or horizontally.

1. vstack()
Functionality: Stacks arrays vertically (row-wise). It combines arrays along the first axis (axis 0), stacking them one on top of the other.
Shape Compatibility: Arrays must have the same number of columns (same second dimension).

In [16]:
#Example
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9]])

# Vertical stacking
result_vstack = np.vstack((arr1, arr2))
print(result_vstack)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


2. hstack()
Functionality: Stacks arrays horizontally (column-wise). It combines arrays along the second axis (axis 1), placing them side by side.
Shape Compatibility: Arrays must have the same number of rows (same first dimension).

In [17]:
#Example
arr3 = np.array([[10], [11]])

# Horizontal stacking
result_hstack = np.hstack((arr1, arr3))
print(result_hstack)


[[ 1  2  3 10]
 [ 4  5  6 11]]


Summary of Differences:

vstack() stacks arrays vertically (along axis 0), increasing the number of rows.

hstack() stacks arrays horizontally (along axis 1), increasing the number of columns.
Both functions require that the dimensions of the arrays be compatible along the non-stacking axis.

In [18]:
#Q8 -  Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.


In NumPy, fliplr() and flipud() are functions used to flip arrays in specific directions:

1. fliplr()
Functionality: Flips the array left to right (horizontally). This means that the columns of the array are reversed.
Effect on Dimensions:
It operates along the second axis (axis 1), meaning it affects the columns.
The number of rows remains unchanged
2. flipud()
Functionality: Flips the array up to down (vertically). This means that the rows of the array are reversed.
Effect on Dimensions:
It operates along the first axis (axis 0), affecting the rows.
The number of columns remains unchanged.

Summary of Differences:
fliplr():
Flips the array horizontally (left to right).
Affects columns (axis 1), leaving the number of rows unchanged.
flipud():
Flips the array vertically (up to down).
Affects rows (axis 0), leaving the number of columns unchanged.

Effects on Various Array Dimensions:

2D Arrays:

fliplr() affects the order of columns, while flipud() affects the order of rows, as shown in the examples above.
3D Arrays:

fliplr() operates on the last dimension (width), and flipud() operates on the first dimension (height). For example, if you have a 3D array (like an image), fliplr() will flip each slice left to right, and flipud() will flip the entire depth of slices up and down.

In [20]:
#example with 3d array

arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6]],

                   [[7, 8, 9],
                    [10, 11, 12]]])

flipped_lr_3d = np.fliplr(arr_3d)
flipped_ud_3d = np.flipud(arr_3d)

print("Original 3D Array:")
print(arr_3d)

print("\nFlipped Left to Right:")
print(flipped_lr_3d)

print("\nFlipped Up to Down:")
print(flipped_ud_3d)


Original 3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Flipped Left to Right:
[[[ 4  5  6]
  [ 1  2  3]]

 [[10 11 12]
  [ 7  8  9]]]

Flipped Up to Down:
[[[ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]]]


In [21]:
#Q9 - Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

The array_split() method in NumPy is used to split an array into multiple sub-arrays. It is particularly useful when you need to partition an array into a specified number of smaller arrays. Here's a detailed overview of its functionality and how it handles uneven splits:

Functionality of array_split()
Basic Syntax:
{[
numpy.array_split(ary, indices_or_sections, axis=0)}]
ary: The input array to be split.
indices_or_sections: This can be an integer (specifying the number of equal sections) or a sequence of indices (indicating where to split the array).
axis: The axis along which to split the array. The default is 0 (the first axis).
Return Value: The method returns a list of sub-arrays. The number of sub-arrays returned depends on the specified indices_or_sections.

Handling Uneven Splits
When you specify the number of sections to split an array, array_split() can handle cases where the array size is not perfectly divisible by the number of sections. Here's how it works:

If the number of elements in the array is not evenly divisible by the number of sections, array_split() will distribute the elements as evenly as possible across the resulting sub-arrays.
The first few sub-arrays may contain one more element than the others.

In [22]:
#example
import numpy as np

# Create an array of 10 elements
array = np.arange(10)

# Split the array into 3 sections
result = np.array_split(array, 3)

print(result)


[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [ ]:
#Q10 -  Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

Vectorization and broadcasting are two powerful concepts in NumPy that significantly enhance the efficiency of array operations. Here's a breakdown of each concept and how they contribute to performance:

Vectorization
Vectorization refers to the ability to perform operations on entire arrays instead of using explicit loops. This takes advantage of NumPy’s optimized C and Fortran libraries under the hood, allowing for faster computations.

Benefits:
Speed: Operations on whole arrays are typically much faster than processing elements one by one using Python loops.
Simplicity: Vectorized code is often more concise and easier to read, leading to fewer chances for bugs.

In [23]:
#example
import numpy as np

# Create two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Vectorized addition
c = a + b  # Result: array([5, 7, 9])


Broadcasting
Broadcasting is a technique that allows NumPy to perform arithmetic operations on arrays of different shapes. It extends the smaller array across the larger array so that they have compatible dimensions for element-wise operations.

Rules for Broadcasting:
If the arrays have different numbers of dimensions, the smaller-dimensional array is padded with ones on the left until both shapes are the same.
Two dimensions are compatible when:
They are equal, or
One of them is 1 (which means it can be stretched to match the other dimension).
Benefits:
Flexibility: It allows for operations on arrays of different shapes without the need for manual reshaping.
Efficiency: By avoiding the creation of copies or large intermediate arrays, broadcasting minimizes memory usage and speeds up operations.

In [25]:
#Example:
import numpy as np

# Create an array and a scalar
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = 2

# Broadcasting scalar addition
c = a + b  # Result: array([[3, 4, 5],
                 #                [6, 7, 8]])

Contribution to Efficient Array Operations
Performance: Both vectorization and broadcasting leverage low-level optimizations, resulting in significantly faster computations compared to traditional loops.
Memory Management: Broadcasting helps reduce memory overhead by avoiding the creation of large, temporary arrays.
Cleaner Code: These techniques enable more readable and maintainable code, allowing developers to express complex operations in fewer lines.

# Practical Questions:


In [26]:
#Q1 - Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns

In [27]:
import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))

# Interchange its rows and columns (transpose)
transposed_array = np.transpose(array)

array, transposed_array


(array([[86, 43, 55],
        [76, 42, 51],
        [49, 56, 38]]),
 array([[86, 76, 49],
        [43, 42, 56],
        [55, 51, 38]]))

In [ ]:
#Q2 -  Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [28]:
# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Reshape it into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)

array_1d, array_2x5, array_5x2


(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]))

In [29]:
#Q3 - Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [30]:
# Create a 4x4 NumPy array with random float values
array_4x4 = np.random.rand(4, 4)

# Add a border of zeros around it to make it a 6x6 array
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

array_4x4, array_6x6


(array([[0.41892913, 0.12792576, 0.33790262, 0.51737579],
        [0.43797034, 0.34088186, 0.98771711, 0.58863888],
        [0.71597128, 0.16189615, 0.06729098, 0.66204436],
        [0.36832423, 0.73839861, 0.33078186, 0.52033992]]),
 array([[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.41892913, 0.12792576, 0.33790262, 0.51737579,
         0.        ],
        [0.        , 0.43797034, 0.34088186, 0.98771711, 0.58863888,
         0.        ],
        [0.        , 0.71597128, 0.16189615, 0.06729098, 0.66204436,
         0.        ],
        [0.        , 0.36832423, 0.73839861, 0.33078186, 0.52033992,
         0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ]]))

In [ ]:
#Q4 - Using NumPy, create an array of integers from 10 to 60 with a step of 5

In [31]:
# Create an array of integers from 10 to 60 with a step of 5 using NumPy
array_step = np.arange(10, 61, 5)

array_step


array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [32]:
#Q5 - Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [33]:
import numpy as np

# Creating a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Applying various case transformations
upper_case = np.char.upper(arr)        # Convert to uppercase
lower_case = np.char.lower(arr)        # Convert to lowercase
title_case = np.char.title(arr)        # Convert to title case
capitalize_case = np.char.capitalize(arr)  # Capitalize first letter of each string
swapcase = np.char.swapcase(arr)      # Swap case of each string

# Displaying the results
print("Original Array:", arr)
print("Uppercase:", upper_case)
print("Lowercase:", lower_case)
print("Title Case:", title_case)
print("Capitalized:", capitalize_case)
print("Swapcase:", swapcase)

Original Array: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']
Capitalized: ['Python' 'Numpy' 'Pandas']
Swapcase: ['PYTHON' 'NUMPY' 'PANDAS']


In [34]:
#Q6 - Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [35]:
import numpy as np

# Step 1: Create a NumPy array of words
words = np.array(['hello', 'world', 'numpy', 'array'])

# Step 2: Insert a space between each character of every word
spaced_words = np.char.join(' ', words)

# Display the results
print("Original Array:", words)
print("Array with spaces:", spaced_words)

Original Array: ['hello' 'world' 'numpy' 'array']
Array with spaces: ['h e l l o' 'w o r l d' 'n u m p y' 'a r r a y']


In [36]:
#Q7 -  Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division

In [37]:
import numpy as np

# Step 1: Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Step 2: Perform element-wise addition
addition_result = array1 + array2
print("Element-wise Addition:\n", addition_result)

# Step 3: Perform element-wise subtraction
subtraction_result = array1 - array2
print("Element-wise Subtraction:\n", subtraction_result)

# Step 4: Perform element-wise multiplication
multiplication_result = array1 * array2
print("Element-wise Multiplication:\n", multiplication_result)

# Step 5: Perform element-wise division
division_result = array1 / array2
print("Element-wise Division:\n", division_result)

Element-wise Addition:
 [[ 8 10 12]
 [14 16 18]]
Element-wise Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Element-wise Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Element-wise Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [ ]:
#Q8 - Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [38]:
import numpy as np

# Step 1: Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Step 2: Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

# Display the results
print("Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)

Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


In [39]:
#Q9 -  Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [40]:
import numpy as np

# Step 1: Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Step 2: Define a function to check if a number is prime
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Step 3: Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

# Display the results
print("Random Integers:\n", random_integers)
print("Prime Numbers:", prime_numbers)

Random Integers:
 [263 608 602 940  77 975 553   0 520 921 592 846  29 785 518 130 120  18
  64 461 894 256 961 321 815 486 582 222 760 262 421 219 433 935  92 432
  87 245 845 975 956 823 317 165 993 474 176 315 341   1 442 996 686 513
 572 985 276 941 960 338  23 235 634 947 989  41 686 816 663 586 426 128
 952 342 450 506 467 824 381  53  86 436 583 142  72 246 445 905 215 542
 579 183 151 646 272 372 555 181 882 575]
Prime Numbers: [263, 29, 461, 421, 433, 823, 317, 941, 23, 947, 41, 467, 53, 151, 181]


In [41]:
#Q10 - Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [42]:
import numpy as np

# Step 1: Create a NumPy array representing daily temperatures for a month (30 days)
# For demonstration, let's generate random temperatures between -10 and 35 degrees Celsius
np.random.seed(0)  # Seed for reproducibility
daily_temperatures = np.random.randint(-10, 36, size=30)

# Step 2: Reshape the array into weeks (4 full weeks + 2 extra days)
# We will create a 5x7 array for convenience, where the last week may have fewer than 7 days
weeks = np.zeros((5, 7))  # Initialize with zeros
weeks[:4, :7] = daily_temperatures[:28].reshape(4, 7)  # Fill first four weeks
weeks[4, :2] = daily_temperatures[28:]  # Fill remaining days into the last week

# Step 3: Calculate weekly averages
weekly_averages = np.mean(weeks, axis=1)

# Display the results
print("Daily Temperatures for the Month:\n", daily_temperatures)
print("\nWeekly Averages:\n", weekly_averages)

Daily Temperatures for the Month:
 [ 34 -10  -7  -7  29  -1   9  11  26  13  -4  14  14   2  -9  28  29  13
  14   7  27  15   3  -2  -1  10   6  -5   5 -10]

Weekly Averages:
 [ 6.71428571 10.85714286 15.57142857  3.71428571 -0.71428571]
